### ISSUE TITLE
Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data

### ISSUE THREAD

**Issue by hiteshk086** [hhromic/e131-node#11]
Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:386:22)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at state.handle.lookup (dgram.js:301:14)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Emitted 'error' event at:
    at Socket.onListenError (dgram.js:386:8)
    at Object.onceWrapper (events.js:285:13)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

Could you please help me to resolved this issue?

**Comment by hhromic** [comment]
Hi, can you copy a snippet of code that produces this error?  A minimal example reproducing the error. Thanks!

**Comment by hhromic** [comment]
Closing due to inactivity.
